### ISSUE TITLE
import the teacher's spec to be able to rake our progress.

### ISSUE THREAD

**Issue by AmandaPerino** [ariel-lima/rails-mister-cocktail#3]

**Comment by ariel-lima** [comment]
echo "gem 'rspec-rails', group: [ :test ]" >> Gemfile
echo "gem 'rails-controller-testing', group: [ :test ]" >> Gemfile
bundle install
rails db:migrate
rails db:test:prepare
git submodule add https://github.com/lewagon/fullstack-challenges-04-Rails-mister-cocktail-specs.git spec
git add .
git commit -m "Prepare rails app with external specs"

**Comment by AmandaPerino** [comment]
Don't forget to Branch first!
